### ISSUE TITLE
[Mod dev] Azurelib and Geckolib crash when loading a geo model

### ISSUE THREAD

**Issue by avetharun** [AzureDoom/AzureLib#12]
Mods used:
[AzureLib](https://modrinth.com/mod/azurelib/version/D0bLIbTK)
[Origins](https://modrinth.com/mod/origins/version/1.10.0)

[Initialization code](https://pastebin.com/g63HhjCk)

Geo models are placed under `assets/originalfur/geo/`

Relevant logs:
```
[10:00:58] [Render thread/ERROR] (Minecraft) Unhandled game exception
 java.lang.IllegalStateException: Some intrusive holders were not registered: [Reference{null=air}]
	at net.minecraft.registry.SimpleRegistry.freeze(SimpleRegistry.java:364) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.9-v2.jar:?]
	at net.minecraft.registry.Registries.freezeRegistries(Registries.java:239) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.9-v2.jar:?]
	at net.minecraft.registry.Registries.bootstrap(Registries.java:223) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.9-v2.jar:?]
	at net.minecraft.client.MinecraftClient.handler$zlj001$fabric-registry-sync-v0$onStart(MinecraftClient.java:6039) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.9-v2.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:781) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.9-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.9-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
[10:00:58] [Render thread/INFO] (Minecraft) Stopping!
[10:00:58] [Render thread/WARN] (azurelib) Correcting config value 'floatArray[0]' from '135.32' to '500.0'
[10:00:58] [Render thread/INFO] (Minecraft) Caught error loading resourcepacks, removing all selected resourcepacks
 java.util.concurrent.CompletionException: mod.azure.azurelib.AzureLibException: originalfur:geo/missing_model.animation.json: Unsupported geometry json version. Supported versions: 1.12.0
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: mod.azure.azurelib.AzureLibException: originalfur:geo/missing_model.animation.json: Unsupported geometry json version. Supported versions: 1.12.0
	at mod.azure.azurelib.cache.AzureLibCache.lambda$loadModels$2(AzureLibCache.java:97) ~[azurelib-D0bLIbTK.jar:?]
	at mod.azure.azurelib.cache.AzureLibCache.lambda$loadResources$5(AzureLibCache.java:112) ~[azurelib-D0bLIbTK.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more
[10:00:58] [Render thread/INFO] (Minecraft) Reloading ResourceManager: vanilla, fabric (cloth-config, fabric-renderer-api-v1, fabric-api-lookup-api-v1, fabric-recipe-api-v1, fabric-client-tags-api-v1, additionalentityattributes, fabric-events-interaction-v0, fabric-rendering-data-attachment-v1, fabric-block-api-v1, fabric-networking-api-v1, cardinal-components-entity, fabric-object-builder-api-v1, fabric-transitive-access-wideners-v1, origins, playerabilitylib, fabric-lifecycle-events-v1, fabricloader, fabric-screen-api-v1, fabric-sound-api-v1, fabric-renderer-indigo, fabric-gametest-api-v1, originalfur, fabric-command-api-v2, fabric-blockrenderlayer-v1, fabric-api-base, azurelib, reach-entity-attributes, fabric-rendering-fluids-v1, fabric-resource-conditions-api-v1, fabric-crash-report-info-v1, fabric-item-api-v1, fabric-loot-api-v2, cardinal-components-base, fabric-message-api-v1, fabric-resource-loader-v0, fabric-rendering-v1, fabric-entity-events-v1, fabric-data-generation-api-v1, fabric-particles-v1, calio, fabric-registry-sync-v0, fabric-models-v0, fabric-key-binding-api-v1, fabric-convention-tags-v1, fabric-item-group-api-v1, fabric-biome-api-v1, fabric-content-registries-v0, fabric-transfer-api-v1, fabric-mining-level-api-v1, fabric-screen-handler-api-v1, fabric-game-rule-api-v1, fabric-dimensions-v1, fabric-api, apoli)
[10:00:58] [Worker-Main-4/INFO] (Minecraft) Found unifont_all_no_pua-15.0.06.hex, loading
[10:00:59] [Render thread/ERROR] (Minecraft) Shutdown failure!
 java.util.ConcurrentModificationException: null
	at java.util.HashMap.forEach(HashMap.java:1424) ~[?:?]
	at net.minecraft.client.texture.TextureManager.close(TextureManager.java:174) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.9-v2.jar:?]
	at net.minecraft.client.MinecraftClient.close(MinecraftClient.java:1138) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.9-v2.jar:?]
	at net.minecraft.client.MinecraftClient.stop(MinecraftClient.java:1113) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.9-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:266) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.9-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
2023-07-17 10:00:59,994 Worker-Main-3 WARN Error parsing URI G:\JavaProjects\OriginalFur\.gradle\loom-cache\log4j.xml

Process finished with exit code 0
```

AzureLib model:
```json
{
	"format_version": "1.12.0",
	"minecraft:geometry": [
		{
			"description": {
				"identifier": "geometry.unknown",
				"texture_width": 64,
				"texture_height": 64,
				"visible_bounds_width": 2,
				"visible_bounds_height": 4.5,
				"visible_bounds_offset": [0, 1.75, 0]
			},
			"bones": [
				{
					"name": "bipedHead",
					"pivot": [0, 24, 0]
				},
				{
					"name": "armorHead",
					"parent": "bipedHead",
					"pivot": [0, 24, 0],
					"cubes": [
						{"origin": [-5, 32, -5], "size": [10, 10, 10], "uv": [0, 0]}
					]
				},
				{
					"name": "bipedBody",
					"pivot": [0, 24, 0]
				},
				{
					"name": "armorBody",
					"parent": "bipedBody",
					"pivot": [0, 24, 0]
				},
				{
					"name": "bipedRightArm",
					"pivot": [-4, 22, 0]
				},
				{
					"name": "armorRightArm",
					"parent": "bipedRightArm",
					"pivot": [-4, 22, 0]
				},
				{
					"name": "bipedLeftArm",
					"pivot": [4, 22, 0]
				},
				{
					"name": "armorLeftArm",
					"parent": "bipedLeftArm",
					"pivot": [4, 22, 0]
				},
				{
					"name": "bipedLeftLeg",
					"pivot": [-2, 12, 0]
				},
				{
					"name": "armorLeftLeg",
					"parent": "bipedLeftLeg",
					"pivot": [-2, 12, 0]
				},
				{
					"name": "armorLeftBoot",
					"parent": "bipedLeftLeg",
					"pivot": [-2, 12, 0]
				},
				{
					"name": "bipedRightLeg",
					"pivot": [2, 12, 0]
				},
				{
					"name": "armorRightLeg",
					"parent": "bipedRightLeg",
					"pivot": [2, 12, 0]
				},
				{
					"name": "armorRightBoot",
					"parent": "bipedRightLeg",
					"pivot": [2, 12, 0]
				}
			]
		}
	]
}
```

Full logs:
https://pastebin.com/ZVTxUNbS

**Comment by AzureDoom** [comment]
Do you have a repo of your mod at all? Just need to see your assets folders

**Comment by avetharun** [comment]
[Yes, I just made one for this issue](https://github.com/avetharun/OriginalFur)

**Comment by AzureDoom** [comment]
I don't see the geo anywhere in there unless you are still uploading?

**Comment by avetharun** [comment]
Apologies, IntelliJ didn't upload the full repo.

**Comment by AzureDoom** [comment]
You can't put the animation file in the geo folder. That needs to go in to it's own animation folder. That's why your crashing

**Comment by avetharun** [comment]
Oh, I misread the error, sorry about that

**Comment by AzureDoom** [comment]
You are good, that's why I wanted to check the assets folder!
