### ISSUE TITLE
AzureLib and Mimic mod together causing Minecraft to infinitely load

### ISSUE THREAD

**Issue by chrissquid** [AzureDoom/AzureLib#13]
Im on 1.19.2 fabric 0.14.22 and for some reason whenever azurelib and [Mimic](https://www.curseforge.com/minecraft/mc-mods/mimic-mod) are installed together, the game upon opening just infinitely reloads itself. Its hard to explain but basically it gets to the screen where it says mojang studios with the red background, it finishes loading, shows the minecraft title screen for half a second and then immediately goes back to the loading screen. For the second it shows the title screen, instead of saying "singleplayer" or anything like that it also just shows empty white squares where the text should be. I've tried multiple different versions of azurelib, 1.0.16, 1.0.27, 1.0.26, 1.0.25, and they are all resulting in the same issue. The error I get says 

`[15:59:15] [Worker-Main-26/INFO]: [STDERR]: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at java.base/java.util.Objects.checkIndex(Objects.java:359)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at java.base/java.util.ArrayList$SubList.get(ArrayList.java:1149)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:306)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:282)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.createFunction(MathBuilder.java:439)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:266)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:308)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:283)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at software.bernie.geckolib3.core.molang.MolangParser.parseSymbolsMolang(MolangParser.java:228)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at software.bernie.geckolib3.core.molang.MolangParser.parseOneLine(MolangParser.java:216)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at software.bernie.geckolib3.core.molang.MolangParser.parseExpression(MolangParser.java:174)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at software.bernie.geckolib3.core.molang.MolangParser.parseJson(MolangParser.java:154)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.parseExpression(JsonKeyFrameUtils.java:179)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJson(JsonKeyFrameUtils.java:57)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJsonToRotationKeyFrames(JsonKeyFrameUtils.java:173)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonAnimationUtils.deserializeJsonToAnimation(JsonAnimationUtils.java:278)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at software.bernie.geckolib3.file.AnimationFileLoader.loadAllAnimations(AnimationFileLoader.java:32)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$reload$0(GeckoLibCache.java:73)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$loadResources$5(GeckoLibCache.java:91)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[15:59:15] [Worker-Main-26/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)`

**Comment by AzureDoom** [comment]
This is an issue with mimics animation file as its broken. Geckolib 1.19.2 fails to catch this where AzureLib properly does. It requires the mimic mod to fix their animation file.
