### ISSUE TITLE
Azurelib

### ISSUE THREAD

**Issue by Wasaberto07** [AzureDoom/AzureLib#50]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-05-08 16:34:45
Description: Rendering overlay

java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.size()" because "animationJsonList" is null
	at mod.azure.azurelib.loading.json.typeadapter.BakedAnimationsAdapter.deserialize(BakedAnimationsAdapter.java:64) ~[azurelib-neo-1.20.1-2.0.19.jar%23400!/:2.0.19] {re:classloading}
	at mod.azure.azurelib.loading.json.typeadapter.BakedAnimationsAdapter.deserialize(BakedAnimationsAdapter.java:40) ~[azurelib-neo-1.20.1-2.0.19.jar%23400!/:2.0.19] {re:classloading}
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%23107!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%23107!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%23107!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar%23107!/:?] {}
	at mod.azure.azurelib.loading.FileLoader.loadAnimationsFile(FileLoader.java:29) ~[azurelib-neo-1.20.1-2.0.19.jar%23400!/:2.0.19] {re:classloading}
	at mod.azure.azurelib.cache.AzureLibCache.lambda$loadAnimations$1(AzureLibCache.java:88) ~[azurelib-neo-1.20.1-2.0.19.jar%23400!/:2.0.19] {re:classloading}
	at mod.azure.azurelib.cache.AzureLibCache.lambda$loadResources$5(AzureLibCache.java:112) ~[azurelib-neo-1.20.1-2.0.19.jar%23400!/:2.0.19] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	AzureLib (azurelib), Version: 2.0.19
		Issue tracker URL: https://github.com/AzureDoom/AzureLib/issues
		at TRANSFORMER/azurelib@2.0.19/mod.azure.azurelib.loading.json.typeadapter.BakedAnimationsAdapter.deserialize(BakedAnimationsAdapter.java:64)
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:957) ~[client-1.20.1-20230612.114412-srg.jar%23590!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:features.gui.hooks.console.GameRendererMixin from mod embeddium,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinTweakFarPlane from mod oculus,pl:mixin:APP:fastload.mixins.json:client.GameRendererMixin from mod fastload,pl:mixin:APP:aoa3.mixins.json:client.patch.GameRendererMixin from mod aoa3,pl:mixin:APP:tslateffectslib.mixins.json:client.GameRendererMixin from mod tslateffectslib,pl:mixin:APP:shouldersurfing.mixins.json:MixinGameRenderer from mod shouldersurfing,pl:mixin:APP:corgilib.mixins.json:client.GameRendererMixin from mod corgilib,pl:mixin:APP:embeddiumplus.mixin.json:TotalDarkness.MixinGameRenderer from mod embeddiumplus,pl:mixin:APP:mixins.satin.client.json:event.GameRendererMixin from mod (unknown),pl:mixin:APP:immersive_aircraft.mixins.json:GameRendererMixin from mod immersive_aircraft,pl:mixin:APP:mixins.artifacts.common.json:item.wearable.nightvisiongoggles.client.GameRendererMixin from mod artifacts,pl:mixin:APP:mixins.essential.json:client.renderer.MixinEntityRenderer from mod essential,pl:mixin:APP:mixins.essential.json:client.renderer.MixinEntityRenderer_Zoom from mod essential,pl:mixin:APP:mixins.essential.json:events.Mixin_RenderTickEvent from mod essential,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat from mod oculus,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin from mod securitycraft,pl:mixin:APP:mixins.essential.json:events.Mixin_GuiDrawScreenEvent_Priority from mod essential,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
-- Overlay render details --
Details:
	Overlay name: net.minecraftforge.client.loading.ForgeLoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:957) ~[client-1.20.1-20230612.114412-srg.jar%23590!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:features.gui.hooks.console.GameRendererMixin from mod embeddium,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinTweakFarPlane from mod oculus,pl:mixin:APP:fastload.mixins.json:client.GameRendererMixin from mod fastload,pl:mixin:APP:aoa3.mixins.json:client.patch.GameRendererMixin from mod aoa3,pl:mixin:APP:tslateffectslib.mixins.json:client.GameRendererMixin from mod tslateffectslib,pl:mixin:APP:shouldersurfing.mixins.json:MixinGameRenderer from mod shouldersurfing,pl:mixin:APP:corgilib.mixins.json:client.GameRendererMixin from mod corgilib,pl:mixin:APP:embeddiumplus.mixin.json:TotalDarkness.MixinGameRenderer from mod embeddiumplus,pl:mixin:APP:mixins.satin.client.json:event.GameRendererMixin from mod (unknown),pl:mixin:APP:immersive_aircraft.mixins.json:GameRendererMixin from mod immersive_aircraft,pl:mixin:APP:mixins.artifacts.common.json:item.wearable.nightvisiongoggles.client.GameRendererMixin from mod artifacts,pl:mixin:APP:mixins.essential.json:client.renderer.MixinEntityRenderer from mod essential,pl:mixin:APP:mixins.essential.json:client.renderer.MixinEntityRenderer_Zoom from mod essential,pl:mixin:APP:mixins.essential.json:events.Mixin_RenderTickEvent from mod essential,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat from mod oculus,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin from mod securitycraft,pl:mixin:APP:mixins.essential.json:events.Mixin_GuiDrawScreenEvent_Priority from mod essential,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23590!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23590!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[a.jar:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin from mod smoothboot,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.16.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.16.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.16.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: vanilla, mod_resources, diagonalblocks:default_block_models, essential

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3657536904 bytes (3488 MiB) / 5402263552 bytes (5152 MiB) up to 15233712128 bytes (14528 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800H with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3050 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x25a2
	Graphics card #0 versionInfo: DriverVersion=31.0.15.5222
	Graphics card #1 name: AMD Radeon(TM) Graphics
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 512.00
	Graphics card #1 deviceId: 0x1638
	Graphics card #1 versionInfo: DriverVersion=31.0.21912.14
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 31421.74
	Virtual memory used (MB): 22551.35
	Swap memory total (MB): 15710.87
	Swap memory used (MB): 1194.32
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx14500M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Loaded Shaderpack: ComplementaryUnbound_r5.1.1 + EuphoriaPatches_1.1
		Profile: ULTRA (+0 options changed by user)
	Launched Version: a
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2 GL version 4.6.0 NVIDIA 552.22, NVIDIA Corporation
	Window size: 925x530
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: es_es
	CPU: 16x AMD Ryzen 7 5800H with Radeon Graphics 
	Sinytra Connector: 1.0.0-beta.28+1.20.1
		SINYTRA CONNECTOR IS PRESENT!
		Please verify issues are not caused by Connector before reporting them to mod authors. If you're unsure, file a report on Connector's issue tracker.
		Connector's issue tracker can be found at https://github.com/Sinytra/Connector/issues.
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.16.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.16.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.16.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.16.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.16.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar essential-loader TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar mixin-transmogrifier TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar connector_loader TRANSFORMATIONSERVICE 
	FML Language Providers: 
		javafml@null
		lowcodefml@null
		minecraft@1.0
		gml@4.0.9

**Comment by AzureDoom** [comment]
This is an issue with whatever mod is using Azurelib, it's not an AzureLib level issue. Please test what AzureLib required mods you have in your pack.
