### ISSUE TITLE
The mod is incompatible, causing a crash

### ISSUE THREAD

**Issue by abm991** [AzureDoom/AzureLib#52]
Hello author, this MOD is not compatible with your support library :https://www.curseforge.com/minecraft/mc-mods/hit-feedback
Problem: When attacking a mob, it immediately crashes

**Comment by AzureDoom** [comment]
Invalid report, no logs

**Comment by abm991** [comment]
[22:15:17] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.11
[22:15:17] [main/INFO]: Loading 61 mods:
	- architectury 9.2.14
	- azurelib 2.0.22
	- fabric-api 0.92.1+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.1+1802ada577
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- hit_feedback 1.20.1-1.0.0
	   \-- reach-entity-attributes 2.4.0
	- java 22
	- minecraft 1.20.1
[22:15:17] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/%e5%bb%96%e4%b8%9c%e5%8d%8e/Desktop/.minecraft/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[22:15:18] [main/INFO]: Compatibility level set to JAVA_16
[22:15:18] [main/INFO]: Compatibility level set to JAVA_17
[22:15:19] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[22:15:20] [main/WARN]: Invalid registry value type detected for PerfOS counters. Should be REG_DWORD. Ignoring: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfOS\Performance\Disable Performance Counters.
[22:15:25] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 185 milliseconds
[22:15:27] [Render thread/INFO]: [STDERR]: [LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.
[22:15:28] [Render thread/INFO]: Environment: authHost='http://localhost:58840/authserver', accountsHost='http://127.0.0.1:58858/https/api.mojang.com', sessionHost='http://127.0.0.1:58858/https/sessionserver.mojang.com', servicesHost='http://127.0.0.1:58858/https/api.minecraftservices.com', name='PROD'
[22:15:28] [Render thread/INFO]: Setting user: abm991
[22:15:28] [Render thread/WARN]: Correcting config value 'disableOptifineWarning' from 'null' to 'false'
[22:15:28] [Render thread/WARN]: Correcting config value 'useVanillaUseKey' from 'null' to 'true'
[22:15:28] [Render thread/INFO]: Registered azurelib config for auto-sync function
[22:15:28] [Render thread/INFO]: Registering C2S receiver with id hit_feedback:main/e821d74c88b73fdaab01e792d4188624
[22:15:28] [Render thread/INFO]: Registering S2C receiver with id hit_feedback:main/e821d74c88b73fdaab01e792d4188624
[22:15:28] [Render thread/INFO]: Registering S2C receiver with id architectury:spawn_entity_packet
[22:15:28] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[22:15:29] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[22:15:31] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric (azurelib, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-tables-v1, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-networking-v0, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, hit_feedback, reach-entity-attributes)
[22:15:31] [Worker-Main-11/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[22:15:31] [Worker-Main-8/WARN]: File hit_feedback:sounds/feedback/metal/failure_1.ogg does not exist, cannot add it to event hit_feedback:feedback.metal.failure
[22:15:31] [Worker-Main-8/WARN]: File hit_feedback:sounds/feedback/metal/failure_2.ogg does not exist, cannot add it to event hit_feedback:feedback.metal.failure
[22:15:31] [Worker-Main-8/WARN]: File hit_feedback:sounds/feedback/metal/failure_3.ogg does not exist, cannot add it to event hit_feedback:feedback.metal.failure
[22:15:31] [Worker-Main-8/WARN]: File hit_feedback:sounds/feedback/metal/failure_4.ogg does not exist, cannot add it to event hit_feedback:feedback.metal.failure
[22:15:31] [Worker-Main-8/WARN]: File hit_feedback:sounds/feedback/metal/failure_5.ogg does not exist, cannot add it to event hit_feedback:feedback.metal.failure
[22:15:31] [Worker-Main-8/WARN]: File hit_feedback:sounds/feedback/metal/failure_6.ogg does not exist, cannot add it to event hit_feedback:feedback.metal.failure
[22:15:31] [Worker-Main-8/WARN]: File hit_feedback:sounds/feedback/metal/failure_7.ogg does not exist, cannot add it to event hit_feedback:feedback.metal.failure
[22:15:31] [Worker-Main-8/WARN]: File hit_feedback:sounds/feedback/metal/failure_8.ogg does not exist, cannot add it to event hit_feedback:feedback.metal.failure
[22:15:32] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[22:15:33] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[22:15:33] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[22:15:33] [Render thread/WARN]: Missing sound for event: hit_feedback:feedback.metal
[22:15:33] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on 扬声器 (Realtek(R) Audio)
[22:15:33] [Render thread/INFO]: Sound engine started
[22:15:33] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[22:15:33] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[22:15:33] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[22:15:33] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[22:15:33] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[22:15:33] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[22:15:33] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[22:15:33] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[22:15:33] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[22:15:34] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[22:15:34] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[22:15:34] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[22:15:34] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[22:17:06] [Render thread/INFO]: Loaded 7 recipes
[22:17:06] [Render thread/INFO]: Loaded 1271 advancements
[22:17:06] [Render thread/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 1.871 ms
[22:17:06] [Server thread/INFO]: Starting integrated minecraft server version 1.20.1
[22:17:06] [Server thread/INFO]: Generating keypair
[22:17:07] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[22:17:10] [Render thread/INFO]: 准备生成区域中：0%
[22:17:10] [Render thread/INFO]: 准备生成区域中：0%
[22:17:10] [Render thread/INFO]: 准备生成区域中：0%
[22:17:10] [Render thread/INFO]: 准备生成区域中：0%
[22:17:10] [Render thread/INFO]: 准备生成区域中：0%
[22:17:10] [Render thread/INFO]: 准备生成区域中：3%
[22:17:10] [Render thread/INFO]: 准备生成区域中：74%
[22:17:11] [Render thread/INFO]: Time elapsed: 3143 ms
[22:17:11] [Server thread/INFO]: Changing view distance to 5, from 10
[22:17:11] [Server thread/INFO]: Changing simulation distance to 12, from 0
[22:17:11] [Server thread/INFO]: abm991[local:E:ebdbd199] logged in with entity id 198 at (28.153813536383595, 79.0, -1.3259152532281164)
[22:17:12] [Server thread/INFO]: abm991加入了游戏
[22:17:12] [Worker-Main-10/INFO]: [STDOUT]: http://localhost:58840/textures/84c70e16e9d3f17e066a4fea89219f2b475e0248ee1fc86802932f00f0e0fdbb
[22:17:12] [Worker-Main-10/INFO]: [STDOUT]: http://localhost:58840/textures/22623dd4b12fa4beb31b173d63f53d955312d6a6f66a721c2ede8b6a1fc943d1
[22:17:12] [Render thread/INFO]: Loaded 43 advancements
[22:17:12] [Render thread/ERROR]: Unreported exception thrown!
java.lang.IllegalArgumentException: Bound must be positive
	at net.minecraft.class_6566.method_43048(class_6566.java:22) ~[client-intermediary.jar:?]
	at mod.chloeprime.hitfeedback.client.particles.EntityPieceParticle.<init>(EntityPieceParticle.java:34) ~[HitFeedback-1.20.1-1.0.0-fabric.jar:?]
	at mod.chloeprime.hitfeedback.client.particles.ParticleEmitterBase.method_3070(ParticleEmitterBase.java:84) ~[HitFeedback-1.20.1-1.0.0-fabric.jar:?]
	at net.minecraft.class_702.method_3057(class_702.java:373) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1946) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
[22:17:13] [Server thread/INFO]: Stopping server
[22:17:13] [Server thread/INFO]: Saving players
[22:17:13] [Server thread/INFO]: Saving worlds
[22:17:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:overworld
[22:17:15] [Server thread/INFO]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:the_nether
[22:17:15] [Server thread/INFO]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:the_end
[22:17:15] [Server thread/INFO]: ThreadedAnvilChunkStorage (新的世界 (2)): All chunks are saved
[22:17:15] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[22:17:15] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[22:17:15] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved

**Comment by abm991** [comment]
This time it's a loading world crash, as opposed to a crash when attacking a creature triggers a particle effect

**Comment by AzureDoom** [comment]
```
java.lang.IllegalArgumentException: Bound must be positive
at net.minecraft.class_6566.method_43048(class_6566.java:22) ~[client-intermediary.jar:?]
at mod.chloeprime.hitfeedback.client.particles.EntityPieceParticle.(EntityPieceParticle.java:34) ~[HitFeedback-1.20.1-1.0.0-fabric.jar:?]
at mod.chloeprime.hitfeedback.client.particles.ParticleEmitterBase.method_3070(ParticleEmitterBase.java:84) 
```
This is an issue with the hitfeedback mod, not this mod.
