### ISSUE TITLE
[BUG] com.google.gson.JsonSyntaxException: Expected vector to be a JsonArray, was an object ({"ve...0]})

### ISSUE THREAD

**Issue by Darkslayer99-beep** [AzureDoom/AzureLib#76]
***ALL INFO MUST BE FILLED IN OR THE ISSUE WILL BE CLOSED AS INVALID***

**Minecraft Info:**
Minecraft Version:
Modloader version: 
Mod version:

**Describe the bug**

**To Reproduce**

**Screenshots**

**Comment by Darkslayer99-beep** [comment]
com.google.gson.JsonSyntaxException: Expected vector to be a JsonArray, was an object ({"ve...0]})
	at net.minecraft.util.GsonHelper.m_13924_(GsonHelper.java:431) ~[client-1.19.2-20220805.130853-srg.jar%23443!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.GsonHelper.m_13933_(GsonHelper.java:437) ~[client-1.19.2-20220805.130853-srg.jar%23443!/:?] {re:classloading,re:mixin}
	at mod.azure.azurelib.loading.json.typeadapter.BakedAnimationsAdapter.buildKeyframeStack(BakedAnimationsAdapter.java:186) ~[azurelib-forge-1.19.2-1.0.38.jar%23310!/:1.0.38] {re:classloading}
	at mod.azure.azurelib.loading.json.typeadapter.BakedAnimationsAdapter.bakeBoneAnimations(BakedAnimationsAdapter.java:101) ~[azurelib-forge-1.19.2-1.0.38.jar%23310!/:1.0.38] {re:classloading}
	at mod.azure.azurelib.loading.json.typeadapter.BakedAnimationsAdapter.bakeAnimation(BakedAnimationsAdapter.java:82) ~[azurelib-forge-1.19.2-1.0.38.jar%23310!/:1.0.38] {re:classloading}
	at mod.azure.azurelib.loading.json.typeadapter.BakedAnimationsAdapter.deserialize(BakedAnimationsAdapter.java:68) ~[azurelib-forge-1.19.2-1.0.38.jar%23310!/:1.0.38] {re:classloading}
	at mod.azure.azurelib.loading.json.typeadapter.BakedAnimationsAdapter.deserialize(BakedAnimationsAdapter.java:40) ~[azurelib-forge-1.19.2-1.0.38.jar%23310!/:1.0.38] {re:classloading}
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar%23127!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%23127!/:?] {re:mixin}
	at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar%23127!/:?] {re:mixin}
	at com.google.gson.Gson.fromJson(Gson.java:1006) ~[gson-2.8.9.jar%23127!/:?] {re:mixin}
	at mod.azure.azurelib.loading.FileLoader.loadAnimationsFile(FileLoader.java:28) ~[azurelib-forge-1.19.2-1.0.38.jar%23310!/:1.0.38] {re:classloading}
	at mod.azure.azurelib.cache.AzureLibCache.lambda$loadAnimations$1(AzureLibCache.java:83) ~[azurelib-forge-1.19.2-1.0.38.jar%23310!/:1.0.38] {re:classloading}
	at mod.azure.azurelib.cache.AzureLibCache.lambda$loadResources$5(AzureLibCache.java:102) ~[azurelib-forge-1.19.2-1.0.38.jar%23310!/:1.0.38] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	AzureLib (azurelib), Version: 1.0.38
		Issue tracker URL: https://github.com/AzureDoom/AzureLib/issues
		at TRANSFORMER/azurelib@1.0.38/mod.azure.azurelib.loading.json.typeadapter.BakedAnimationsAdapter.buildKeyframeStack(BakedAnimationsAdapter.java:186)
Stacktrace:
	at net.minecraft.util.GsonHelper.m_13924_(GsonHelper.java:431) ~[client-1.19.2-20220805.130853-srg.jar%23443!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.GsonHelper.m_13933_(GsonHelper.java:437) ~[client-1.19.2-20220805.130853-srg.jar%23443!/:?] {re:classloading,re:mixin}
	at mod.azure.azurelib.loading.json.typeadapter.BakedAnimationsAdapter.buildKeyframeStack(BakedAnimationsAdapter.java:186) ~[azurelib-forge-1.19.2-1.0.38.jar%23310!/:1.0.38] {re:classloading}
Mixins in Heaven: None found
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.screens.LoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:888) ~[client-1.19.2-20220805.130853-srg.jar%23443!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGameRenderer,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:mixins.oculus.json:MixinTweakFarPlane,pl:mixin:APP:controllable.mixins.json:client.GameRendererMixin,pl:mixin:APP:cgm.mixins.json:client.GameRendererMixin,pl:mixin:APP:forge-mca.mixin.json:client.MixinGameRenderer,pl:mixin:APP:jeg.mixins.json:client.GameRendererMixin,pl:mixin:APP:mtr.mixins.json:GameRendererMixin,pl:mixin:APP:ava.mixins.json:client.GameRendererMixin,pl:mixin:APP:mixins.essential.json:client.renderer.MixinEntityRenderer_Zoom,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:APP:mixins.essential.json:events.Mixin_GuiDrawScreenEvent_Priority,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23443!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:combatroll.mixins.json:MinecraftClientMixin,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:enhancedvisuals.mixins.json:MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMinecraft,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.MinecraftMixin,pl:mixin:APP:cgm.mixins.json:client.MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:jeg.mixins.json:client.MinecraftMixin,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:mixins.essential.json:client.Mixin_RunEssentialTasks,pl:mixin:APP:mixins.essential.json:client.MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_FixKeybindUnpressedInEmoteWheel,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_RecalculateMenuScale,pl:mixin:APP:mixins.essential.json:compatibility.vanilla.Mixin_WorkaroundBrokenFramebufferBlitBlending,pl:mixin:APP:mixins.essential.json:events.Mixin_RenderTickEvent,pl:mixin:APP:mixins.essential.json:feature.skin_overwrites.Mixin_InstallTrustingServicesKeyInfo,pl:mixin:APP:sound_physics_remastered.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23443!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:combatroll.mixins.json:MinecraftClientMixin,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:enhancedvisuals.mixins.json:MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMinecraft,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.MinecraftMixin,pl:mixin:APP:cgm.mixins.json:client.MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:jeg.mixins.json:client.MinecraftMixin,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:mixins.essential.json:client.Mixin_RunEssentialTasks,pl:mixin:APP:mixins.essential.json:client.MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_FixKeybindUnpressedInEmoteWheel,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_RecalculateMenuScale,pl:mixin:APP:mixins.essential.json:compatibility.vanilla.Mixin_WorkaroundBrokenFramebufferBlitBlending,pl:mixin:APP:mixins.essential.json:events.Mixin_RenderTickEvent,pl:mixin:APP:mixins.essential.json:feature.skin_overwrites.Mixin_InstallTrustingServicesKeyInfo,pl:mixin:APP:sound_physics_remastered.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23443!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23443!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.4.4.jar%23101!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

Mixins in Heaven:
	net.minecraft.client.renderer.GameRenderer:
		com.mrcrayfish.controllable.mixin.client.GameRendererMixin (controllable.mixins.json)
		gg.essential.mixins.transformers.client.renderer.MixinEntityRenderer_Zoom (mixins.essential.json)
		pellucid.ava.mixins.client.GameRendererMixin (ava.mixins.json)
		net.mehvahdjukaar.supplementaries.mixins.GameRendererMixin (supplementaries-common.mixins.json)
		com.simibubi.create.foundation.mixin.accessor.GameRendererAccessor (create.mixins.json)
		net.geforcemods.securitycraft.mixin.camera.GameRendererMixin (securitycraft.mixins.json)
		ttv.migami.jeg.mixin.client.GameRendererMixin (jeg.mixins.json)
		com.railwayteam.railways.mixin.conductor_possession.MixinGameRenderer (railways-common.mixins.json)
		net.coderbot.iris.mixin.MixinTweakFarPlane (mixins.oculus.json)
		net.coderbot.iris.mixin.GameRendererAccessor (mixins.oculus.json)
		net.coderbot.iris.mixin.MixinGameRenderer_NightVisionCompat (mixins.oculus.json)
		net.coderbot.iris.mixin.MixinModelViewBobbing (mixins.oculus.json)
		net.coderbot.iris.mixin.MixinGameRenderer (mixins.oculus.json)
		com.mrcrayfish.guns.mixin.client.GameRendererMixin (cgm.mixins.json)
		forge.net.mca.mixin.client.MixinGameRenderer (forge-mca.mixin.json)
		mtr.mixin.GameRendererMixin (mtr.mixins.json)
		gg.essential.mixins.transformers.events.Mixin_GuiDrawScreenEvent_Priority (mixins.essential.json)
		com.simibubi.create.foundation.mixin.client.GameRendererMixin (create.mixins.json)
	net.minecraft.client.Minecraft:
		me.jellysquid.mods.sodium.mixin.core.MixinMinecraftClient (rubidium.mixins.json)
		org.embeddedt.modernfix.common.mixin.feature.measure_time.MinecraftMixin (modernfix-common.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_PipelineManagement (mixins.oculus.json)
		net.bettercombat.mixin.client.MinecraftClientInject (bettercombat.mixins.json)
		org.embeddedt.modernfix.common.mixin.perf.blast_search_trees.MinecraftMixin (modernfix-common.mixins.json)
		dev.architectury.mixin.forge.MixinMinecraft (architectury.mixins.json)
		team.creative.itemphysic.mixin.MinecraftMixin (itemphysic.mixins.json)
		org.embeddedt.modernfix.common.mixin.bugfix.world_leaks.MinecraftMixin (modernfix-common.mixins.json)
		com.sonicether.soundphysics.mixin.MinecraftMixin (sound_physics_remastered.mixins.json)
		net.combatroll.mixin.MinecraftClientMixin (combatroll.mixins.json)
		ttv.migami.jeg.mixin.client.MinecraftMixin (jeg.mixins.json)
		net.bettercombat.mixin.client.MinecraftClientAccessor (bettercombat.mixins.json)
		gg.essential.mixins.transformers.events.Mixin_RenderTickEvent (mixins.essential.json)
		tschipp.carryon.mixin.MinecraftMixin (carryon.mixins.json)
		gg.essential.mixins.transformers.client.gui.Mixin_FixKeybindUnpressedInEmoteWheel (mixins.essential.json)
		team.creative.enhancedvisuals.mixin.MinecraftMixin (enhancedvisuals.mixins.json)
		com.mrcrayfish.guns.mixin.client.MinecraftMixin (cgm.mixins.json)
		gg.essential.mixins.transformers.client.MixinMinecraft (mixins.essential.json)
		com.railwayteam.railways.mixin.conductor_possession.MixinMinecraft (railways-common.mixins.json)
		net.geforcemods.securitycraft.mixin.camera.MinecraftMixin (securitycraft.mixins.json)
		com.mrcrayfish.controllable.mixin.client.MinecraftMixin (controllable.mixins.json)
		gg.essential.mixins.transformers.client.Mixin_RunEssentialTasks (mixins.essential.json)
		gg.essential.mixins.transformers.compatibility.vanilla.Mixin_WorkaroundBrokenFramebufferBlitBlending (mixins.essential.json)
		org.embeddedt.modernfix.common.mixin.bugfix.concurrency.MinecraftMixin (modernfix-common.mixins.json)
		dev.lambdaurora.lambdynlights.mixin.MinecraftClientMixin (dynamiclightsreforged.mixins.json)
		com.simibubi.create.foundation.mixin.client.WindowResizeMixin (create.mixins.json)
		net.darkhax.bookshelf.mixin.client.AccessorMinecraft (bookshelf.common.mixins.json)
		org.embeddedt.modernfix.forge.mixin.feature.measure_time.MinecraftMixin_Forge (modernfix-forge.mixins.json)
		com.jozufozu.flywheel.mixin.PausedPartialTickAccessor (flywheel.mixins.json)
		gg.essential.mixins.transformers.client.gui.Mixin_RecalculateMenuScale (mixins.essential.json)
		org.embeddedt.modernfix.common.mixin.perf.dedicated_reload_executor.MinecraftMixin (modernfix-common.mixins.json)
		gg.essential.mixins.transformers.feature.skin_overwrites.Mixin_InstallTrustingServicesKeyInfo (mixins.essential.json)
		com.legacy.mining_helmet.mixin.MinecraftMixin (mining_helmet.mixins.json)
	net.minecraft.client.main.Main:
		com.jozufozu.flywheel.mixin.ClientMainMixin (flywheel.mixins.json)

**Comment by Darkslayer99-beep** [comment]
how do I fix it

**Comment by AzureDoom** [comment]
Is this a mod you are developing or in a pack? If in a pack, find what mods are using this as one is shipping a broken animations.

**Comment by Darkslayer99-beep** [comment]
A mod pack, the only mod using it is sculk horde.

**Comment by AzureDoom** [comment]
If you are using any geckolib powered ones, disable them and enable them 1 by 1.
