### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Monocucuy** [AzureDoom/AzureLib#9]
---- Minecraft Crash Report ----
// There are four lights!

Time: 2023-06-19 17:30:02
Description: Rendering overlay

com.google.gson.JsonSyntaxException: Expected pre to be a JsonArray, was an object ({"ve...1]})
	at net.minecraft.util.GsonHelper.m_13924_(GsonHelper.java:431) ~[client-1.19.2-20220805.130853-srg.jar%23517!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.GsonHelper.m_13933_(GsonHelper.java:437) ~[client-1.19.2-20220805.130853-srg.jar%23517!/:?] {re:classloading,re:mixin}
	at mod.azure.azurelib.loading.json.typeadapter.BakedAnimationsAdapter.getTripletObj(BakedAnimationsAdapter.java:137) ~[azurelib-forge-1.19.2-1.0.23.jar%23352!/:1.0.23] {re:classloading}
	at mod.azure.azurelib.loading.json.typeadapter.BakedAnimationsAdapter.bakeBoneAnimations(BakedAnimationsAdapter.java:102) ~[azurelib-forge-1.19.2-1.0.23.jar%23352!/:1.0.23] {re:classloading}
	at mod.azure.azurelib.loading.json.typeadapter.BakedAnimationsAdapter.bakeAnimation(BakedAnimationsAdapter.java:82) ~[azurelib-forge-1.19.2-1.0.23.jar%23352!/:1.0.23] {re:classloading}
	at mod.azure.azurelib.loading.json.typeadapter.BakedAnimationsAdapter.deserialize(BakedAnimationsAdapter.java:68) ~[azurelib-forge-1.19.2-1.0.23.jar%23352!/:1.0.23] {re:classloading}
	at mod.azure.azurelib.loading.json.typeadapter.BakedAnimationsAdapter.deserialize(BakedAnimationsAdapter.java:40) ~[azurelib-forge-1.19.2-1.0.23.jar%23352!/:1.0.23] {re:classloading}
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar%23127!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%23127!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar%23127!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:1006) ~[gson-2.8.9.jar%23127!/:?] {}
	at mod.azure.azurelib.loading.FileLoader.loadAnimationsFile(FileLoader.java:28) ~[azurelib-forge-1.19.2-1.0.23.jar%23352!/:1.0.23] {re:classloading}
	at mod.azure.azurelib.cache.AzureLibCache.lambda$loadAnimations$1(AzureLibCache.java:90) ~[azurelib-forge-1.19.2-1.0.23.jar%23352!/:1.0.23] {re:classloading}
	at mod.azure.azurelib.cache.AzureLibCache.lambda$loadResources$5(AzureLibCache.java:112) ~[azurelib-forge-1.19.2-1.0.23.jar%23352!/:1.0.23] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.util.GsonHelper.m_13924_(GsonHelper.java:431) ~[client-1.19.2-20220805.130853-srg.jar%23517!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.GsonHelper.m_13933_(GsonHelper.java:437) ~[client-1.19.2-20220805.130853-srg.jar%23517!/:?] {re:classloading,re:mixin}
	at mod.azure.azurelib.loading.json.typeadapter.BakedAnimationsAdapter.getTripletObj(BakedAnimationsAdapter.java:137) ~[azurelib-forge-1.19.2-1.0.23.jar%23352!/:1.0.23] {re:classloading}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.screens.LoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:888) ~[client-1.19.2-20220805.130853-srg.jar%23517!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23517!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23517!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23517!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23517!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.14.jar%23101!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default, Mod Resources, cullleaves:smartleaves, EatingAnimations Compat, EmbellishedStone-1.19-1.0.0.zip, MandalasGUI_Legacy+Modded_Dakmode_v4.2.zip, Mods-Translators-plus-331mods.zip, Pixelated_v1.3.1_EnhancedVisuals(nox_cgt).zip, TZP_1.19.2_2.6.zip, [1.3] Enhanced Boss Bars.zip, Essential (forge_1.19.2).jar
	Recovery: Yes
	Recovery reason: java.util.concurrent.CompletionException: com.google.gson.JsonSyntaxException: Expected pre to be a JsonArray, was an object ({"ve...1]})
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: com.google.gson.JsonSyntaxException: Expected pre to be a JsonArray, was an object ({"ve...1]})
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.GsonHelper.m_13924_(GsonHelper.java:431)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.GsonHelper.m_13933_(GsonHelper.java:437)
	at TRANSFORMER/azurelib@1.0.23/mod.azure.azurelib.loading.json.typeadapter.BakedAnimationsAdapter.getTripletObj(BakedAnimationsAdapter.java:137)
	at TRANSFORMER/azurelib@1.0.23/mod.azure.azurelib.loading.json.typeadapter.BakedAnimationsAdapter.bakeBoneAnimations(BakedAnimationsAdapter.java:102)
	at TRANSFORMER/azurelib@1.0.23/mod.azure.azurelib.loading.json.typeadapter.BakedAnimationsAdapter.bakeAnimation(BakedAnimationsAdapter.java:82)
	at TRANSFORMER/azurelib@1.0.23/mod.azure.azurelib.loading.json.typeadapter.BakedAnimationsAdapter.deserialize(BakedAnimationsAdapter.java:68)
	at TRANSFORMER/azurelib@1.0.23/mod.azure.azurelib.loading.json.typeadapter.BakedAnimationsAdapter.deserialize(BakedAnimationsAdapter.java:40)
	at MC-BOOTSTRAP/com.google.gson@2.8.9/com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at MC-BOOTSTRAP/com.google.gson@2.8.9/com.google.gson.Gson.fromJson(Gson.java:963)
	at MC-BOOTSTRAP/com.google.gson@2.8.9/com.google.gson.Gson.fromJson(Gson.java:1034)
	at MC-BOOTSTRAP/com.google.gson@2.8.9/com.google.gson.Gson.fromJson(Gson.java:1006)
	at TRANSFORMER/azurelib@1.0.23/mod.azure.azurelib.loading.FileLoader.loadAnimationsFile(FileLoader.java:28)
	at TRANSFORMER/azurelib@1.0.23/mod.azure.azurelib.cache.AzureLibCache.lambda$loadAnimations$1(AzureLibCache.java:90)
	at TRANSFORMER/azurelib@1.0.23/mod.azure.azurelib.cache.AzureLibCache.lambda$loadResources$5(AzureLibCache.java:112)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 661954944 bytes (631 MiB) / 2046820352 bytes (1952 MiB) up to 5570035712 bytes (5312 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 3.41
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c03
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3623
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 29127.07
	Virtual memory used (MB): 21287.97
	Swap memory total (MB): 12800.00
	Swap memory used (MB): 189.92
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5312m -Xms256m
	Loaded Shaderpack: ComplementaryShaders_v4.7.1.zip
		Profile: Custom (+34 options changed by user)
	NEC status: Has NEC: INVALID
	Launched Version: forge-43.2.14
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 3.2.0 NVIDIA 536.23, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0

**Comment by AzureDoom** [comment]
This likely a mod with a bad animation file, you'll need to enable the mods using Geckolib in small groups with Azurelib to find it.
